export const LOGIN = "LOGIN";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const OTP_SENT = "OTP_SENT";
export const OTP_SENT_FAILED = "OTP_SENT_FAILED";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED";
export const LOGOUT = "LOGOUT";

export const REGISTER_USER = "register_user";
export const REGISTER_USER_SUCCESSFUL = "register_user_successfull";
export const REGISTER_USER_FAILED = "register_user_failed";
// export const FETCH_FAILED_TRANSACTIONS = "FETCH_FAILED_TRANSACTIONS";
export const FETCH_COMPLETED_TRANSACTIONS = "FETCH_COMPLETED_TRANSACTIONS";
export const FETCH_REFUNDED_TRANSACTIONS = "FETCH_REFUNDED_TRANSACTIONS";
export const FETCH_COMPLETED_TRANSACTIONS_FAILED = "FETCH_COMPLETED_TRANSACTIONS_FAILED";
export const FETCH_FAILED_TRANSACTIONS = "FETCH_FAILED_TRANSACTIONS";
export const FETCH_FAILED_TRANSACTIONS_FAILED = "FETCH_FAILED_TRANSACTIONS_FAILED";

export const GET_PROFILE = "GET_PROFILE";
export const USER_PROFILE = "USER_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_ERRORS = "PROFILE_ERRORS";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_EDIT_UPI_MODAL = "SHOW_EDIT_UPI_MODAL";
export const HIDE_EDIT_UPI_MODAL = "HIDE_EDIT_UPI_MODAL";

export const DOWNLOAD_QR = "DOWNLOAD_QR";
export const DOWNLOAD_QR_FAILED = "DOWNLOAD_QR_FAILED";
export const GENERATE_REPORTS = "GENERATE_REPORTS";
export const GENERATE_REPORTS_SUCCESS = "GENERATE_REPORTS_SUCCESS";
export const GENERATE_REPORTS_FAILED = "GENERATE_REPORTS_FAILED";
export const FETCH_REPORTS = "FETCH_REPORTS";
export const FETCH_REPORTS_FAILED = "FETCH_REPORTS_FAILED";
export const SETTLEMENT_LOADING = "SETTLEMENT_LOADING";
export const FETCH_SETTLEMENT_TRANSACTIONS = "FETCH_SETTLEMENT_TRANSACTIONS";
export const FETCH_SETTLEMENT_TRANSACTIONS_FAILED =
  "FETCH_SETTLEMENT_TRANSACTIONS_FAILED";

export const ADD_BANK_DETAILS = "ADD_BANK_DETAILS";
export const ADD_BANK_DETAILS_FAILED = "ADD_BANK_DETAILS_FAILED";
export const FETCH_BANK_DETAILS = "FETCH_BANK_DETAILS";

export const FETCH_BANK_DETAILS_FAILED = "FETCH_BANK_DETAILS_FAILED";
export const CHANGE_DEFAULT_BANK = "CHANGE_DEFAULT_BANK";
export const CHANGE_DEFAULT_BANK_FAILED = "CHANGE_DEFAULT_BANK_FAILED";

export const ORDER_LOADING = "ORDER_LOADING";
export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const TOTAL_SUM = "TOTAL_SUM";
export const TOTAL_COMPLETED_SUM = "TOTAL_COMPLETED_SUM";
export const TOTAL_COMPLETED_TRANSACTIONS = "TOTAL_COMPLETED_TRANSACTIONS";
export const TOTAL_FAILED_SUM = "TOTAL_FAILED_SUM";

export const FETCH_SINGLE_ORDER = "FETCH_SINGLE_ORDER";
export const FETCH_SINGLE_ORDER_FAILED = "FETCH_SINGLE_ORDER_FAILED";
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
export const CHANGE_ORDER_STATUS_FAILED = "CHANGE_ORDER_STATUS_FAILED";

export const SUPPORT_LOADING = "SUPPORT_LOADING";
export const ADD_TICKET = "ADD_TICKET";
export const ADD_TICKET_FAILED = "ADD_TICKET_FAILED";
export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKETS_FAILED = "GET_TICKETS_FAILED";
export const GET_TICKET = "GET_TICKET";
export const GET_TICKET_FAILED = "GET_TICKET_FAILED";
export const ADD_TICKET_CONVERSATION = "ADD_TICKET_CONVERSATION";
export const ADD_TICKET_CONVERSATION_FAILED = "ADD_TICKET_CONVERSATION_FAILED";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
// feteching data using id
export const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID";
export const PRODUCTS_BY_ID_LOADING = "PRODUCTS_BY_ID_LOADING";
export const PRODUCTS_BY_ID_FAILED = "PRODUCTS_BY_ID_FAILED";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
// fetching cagtegory data
export const GET_PRODUCTCATEGORY = "GET_PRODUCTCATEGORY";
export const GET_PRODUCTCATEGORY_FAILED = "GET_PRODUCTCATEGORY_FAILED";

export const FAQ_LOADING = "FAQ_LOADING";
export const FETCH_FAQ = "FETCH_FAQ";
export const FETCH_FAQ_FAILED = "FETCH_FAQ_FAILED";

export const ORDER_TRANSACTIONS = "ORDER_TRANSACTIONS";
export const ORDER_TRANSACTIONS_STATUS = "ORDER_TRANSACTIONS_STATUS";
export const ORDER_TRANSACTIONS_LOADINNG = "ORDER_TRANSACTIONS_LOADINNG";
export const ORDER_TRANSACTIONS_FAILD = "ORDER_TRANSACTIONS_FAILD";
export const FETCH_SINGLE_TRANSACTIONS = "FETCH_SINGLE_ORDER";
export const FETCH_SINGLE_TRANSACTIONS_FAILED = "FETCH_SINGLE_ORDER_FAILED";
export const ORDER_TRANSACTIONS_CHANGE_STATUS =
  "ORDER_TRANSACTIONS_CHANGE_STATUS";
export const CHANGE_ORDER_TRANSACTSTATUS_FAILED =
  "CHANGE_ORDER_TRANSACTSTATUS_FAILED";
